cafeorders/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("orders.urls", namespace="orders")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter

from orders.views import (home_page, UpdateOrderView,
                          calculate_total_revenue, OrderListView,
                          OrderDetailView, CreateOrderView,
                          DeleteOrderView, SearchOrderView)
from orders.api_views import OrderViewSet, ItemViewSet

app_name = "orders"

router = DefaultRouter()
router.register(r'orders', OrderViewSet)
router.register(r'items', ItemViewSet)

urlpatterns = [
    path("", home_page, name="home_page"),

    path("orders/", OrderListView.as_view(),
         name="orders_list"),
    path("orders/order/<int:order_pk>",
         OrderDetailView.as_view(),
         name="order_detail"),
    path("orders/order/create_order",
         CreateOrderView.as_view(),
         name="create_order"),
    path('api/', include(router.urls))
]

ajax_urls = [
    path("orders/ajax/search_order/",
         SearchOrderView.as_view(),
         name="search_order"),
    path("orders/ajax/change_order_status/<int:order_pk>",
         UpdateOrderView.as_view(),
         name="change_order_status"),
    path("orders/order/delete_order/<int:order_pk>",
         DeleteOrderView.as_view(),
         name="delete_order"),
    path("orders/ajax/calculate_total_revenue",
         calculate_total_revenue,
         name="calculate_total_revenue"
         )
]

urlpatterns += ajax_urls

orders/models.py
from django.db import models
from django.shortcuts import reverse

class Item(models.Model):
    name = models.CharField(max_length=155,
                            verbose_name="Название")
    price = models.DecimalField(max_digits=8,
                                decimal_places=2,
                                verbose_name="Стоимость")

    def __str__(self):
        return f"Блюдо: {self.name}. Стоимость: {self.price}"

    class Meta:
        verbose_name = "Блюдо"
        verbose_name_plural = "Блюда"


class Order(models.Model):
    STATUS_CHOICES = [
        ('pending', 'В ожидании'),
        ('ready', 'Готово'),
        ('paid', 'Оплачено'),
    ]

    table_number = models.PositiveIntegerField(verbose_name="Номер стола",
                                               unique=True)
    total_price = models.DecimalField(max_digits=10,
                                      decimal_places=2,
                                      default=0,
                                      verbose_name="Сумма заказа")
    status = models.CharField(max_length=7,
                              choices=STATUS_CHOICES,
                              default="pending", verbose_name="Статус")
    items = models.ManyToManyField(to=Item)

    def __str__(self):
        return f"Заказ #{self.id}. Статус: {self.status}"

    def get_absolute_url(self):
        return reverse("orders:order_detail", kwargs={
            "order_pk": self.pk
        })

    class Meta:
        verbose_name = "Заказ"
        verbose_name_plural = "Заказы"

orders/forms.py
from django import forms
from django.core.exceptions import ValidationError

from orders.models import Order, Item


class CreateOrderForm(forms.ModelForm):
    items = forms.ModelMultipleChoiceField(
        queryset=Item.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        error_messages={
            'required': 'Заказ не может быть пустым.',  # Кастомное сообщение
        }
    )

    class Meta:
        model = Order
        fields = ["table_number", "items"]
        widgets = {
            "table_number": forms.NumberInput(attrs={
                'class': 'form-control w-25',
                'placeholder': 'Номер стола'
            }),
        }

orders/views.py
import json
from django.views import View
from django.http import HttpRequest, HttpResponse, HttpResponseRedirect, QueryDict
from django.http.response import HttpResponseNotAllowed
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse
from django.db.models import Sum
from orders.models import Order
from orders.forms import CreateOrderForm
from orders.ajax_responses import ajax_response


def home_page(request: HttpRequest):
    """
    Отображает главную страницу приложения.

    Args:
        request (HttpRequest): Объект запроса Django.

    Returns:
        HttpResponse: Рендер шаблона главной страницы.
        HttpResponseNotAllowed: Если метод запроса не GET.
    """
    if request.method != "GET":
        return HttpResponseNotAllowed(permitted_methods=["GET"])

    return render(request, "orders/home_page.html")


class BaseOrderView(View):
    """
    Базовый класс для views, работающих с заказами

    Attributes:
        model: Модель, с которой работает View (Order)
        form_class: Класс формы для создания нового заказа
        template_name (str): Имя шаблона для рендера (определяется в дочерних классах)
    """
    model = Order
    form_class = CreateOrderForm
    template_name = None

    def get_context_data(self, **kwargs):
        """
        Возвращает контекст для шаблонов

        Args:
            **kwargs: Дополнительные данные для контекста.

        Returns:
            dict: Контекст для шаблона.
        """
        return kwargs


class OrderListView(BaseOrderView):
    """
    View для отображения списка заказов

    Attributes:
        template_name (str): Имя шаблона для отображения списка заказов.
    """
    template_name = "orders/orders_list.html"

    def get(self, request: HttpRequest, *args, **kwargs):
        """
        Обрабатывает GET-запрос для отображения списка заказов.

        Если в запросе передан параметр 'status', возвращает заказы с указанным статусом.

        Args:
            request (HttpRequest): Объект запроса Django.
            *args: Дополнительные позиционные аргументы.
            **kwargs: Дополнительные именованные аргументы.

        Returns:
            HttpResponse: Рендер шаблона с контекстом, содержащим список заказов.

        """
        status = request.GET.get("status")
        if status:
            orders = self.model.objects.filter(status=status)
            status = dict(Order.STATUS_CHOICES).get(status)
        else:
            orders = self.model.objects.all()

        context = self.get_context_data(orders=orders, status=status)

        return render(request, self.template_name, context=context)


class OrderDetailView(BaseOrderView):
    """
    View для отображения деталей конкретного заказа.

    Attributes:
        template_name (str): Имя шаблона для отображения деталей заказа.
    """
    template_name = "orders/order_detail.html"

    def get(self, request: HttpRequest, order_pk: int, *args, **kwargs):
        """
        Обрабатывает GET-запрос для отображения деталей заказа.

        Args:
            request (HttpRequest): Объект запроса Django.
            order_pk (int): ID заказа.
            *args: Дополнительные позиционные аргументы.
            **kwargs: Дополнительные именованные аргументы.

        Returns:
            HttpResponse: Рендер шаблона с контекстом, содержащим данные заказа и URL для изменения статуса.
        """
        order = get_object_or_404(
            klass=self.model, pk=order_pk
        )

        context = self.get_context_data(
            order=order,
            url_for_change_order_status=reverse(
                "orders:change_order_status", args=[order.pk]
            )
        )
        return render(request,
                      self.template_name,
                      context=context
                      )


class CreateOrderView(BaseOrderView):
    """
    View для создания нового заказа.

    Attributes:
        template_name (str): Имя шаблона для отображения формы создания заказа.
    """
    template_name = "orders/order_create.html"

    def get(self, request: HttpRequest):
        """
        Обрабатывает GET-запрос для отображения формы создания заказа.

        Args:
            request (HttpRequest): Объект запроса Django.

        Returns:
            HttpResponse: Рендер шаблона с формой создания заказа.
        """
        form = self.form_class()
        context = self.get_context_data(
            form=form
        )
        return render(request,
                      self.template_name,
                      context=context
                      )

    def post(self, request: HttpRequest, *args, **kwargs):
        """
        Обрабатывает POST-запрос для создания нового заказа.

        Если данные формы валидны, создает заказ и перенаправляет на его детальную страницу.
        Иначе возвращает форму с ошибками.

        Args:
            request (HttpRequest): Объект запроса Django.
            *args: Дополнительные позиционные аргументы.
            **kwargs: Дополнительные именованные аргументы.

        Returns:
            HttpResponseRedirect: Перенаправление на страницу созданного заказа.
            HttpResponse: Рендер шаблона с формой, если данные невалидны.
        """
        form = self.form_class(request.POST)
        if form.is_valid():
            new_order = form.save()
            redirect_url = reverse("orders:order_detail", args=[new_order.pk])
            return redirect(redirect_url)
        context = self.get_context_data(form=form)
        return render(request, self.template_name, context=context)


# Views для AJAX

class DeleteOrderView(BaseOrderView):
    """
    View для удаления заказа.
    """
    def delete(self, request: HttpRequest, order_pk: int, *args, **kwargs):
        """
        Обрабатывает DELETE-запрос для удаления заказа.

        Args:
            request (HttpRequest): Объект запроса Django.
            order_pk (int): ID заказа для удаления.
            *args: Дополнительные позиционные аргументы.
            **kwargs: Дополнительные именованные аргументы.

        Returns:
            JsonResponse: JSON-ответ с результатом операции.
        """
        try:
            order = self.model.objects.get(pk=order_pk)
        except self.model.DoesNotExist:
            return ajax_response.not_found(
                message="Заказ не найден"
            )

        order.delete()
        return ajax_response.success_request(
            message=f"Заказ №{order_pk} удален.\nСейчас вы будете перенаправлены к списку заказов."
        )


class UpdateOrderView(BaseOrderView):
    """
    View для изменения статуса заказа
    """
    def patch(self, request: HttpRequest, order_pk):
        """
        Обрабатывает PATCH-запрос для изменения статуса заказа.

        Args:
            request (HttpRequest): Объект запроса Django.
            order_pk (int): ID заказа для обновления.

        Returns:
            JsonResponse: JSON-ответ с результатом операции.
        """
        allowed_statuses = dict(Order.STATUS_CHOICES)

        try:
            data = json.loads(request.body.decode('utf-8'))
            new_status = data.get("new_status")
        except json.JSONDecodeError:
            return ajax_response.bad_request()

        if not new_status or new_status not in allowed_statuses.keys():
            return ajax_response.bad_request()

        try:
            order = self.model.objects.get(pk=order_pk)
        except self.model.DoesNotExist:
            return ajax_response.not_found(
                message=f"Заказ не найден"
            )
        order.status = new_status
        order.save()
        return ajax_response.success_request(
            message=f"Статус успешно обновлен_{allowed_statuses.get(new_status)}"
        )


class SearchOrderView(BaseOrderView):
    """
    View для поиска заказов по ID, номеру стола или статусу.
    """
    def get(self, request: HttpRequest, *args, **kwargs):
        """
        Обрабатывает GET-запрос для поиска заказов.

        Args:
            request (HttpRequest): Объект запроса Django.
            *args: Дополнительные позиционные аргументы.
            **kwargs: Дополнительные именованные аргументы.

        Returns:
            JsonResponse: JSON-ответ с результатами поиска или ошибкой.
        """

        search_type = request.GET.get("orderSearchType")
        search_params = request.GET.get("search_val")

        if not search_type or not search_params:
            return ajax_response.bad_request_with_message(
                message="No required parameters"
            )

        if search_type == "by_id":
            return self._search_by_id(order_pk=search_params)
        elif search_type == "by_table":
            return self._search_by_table(table_id=search_params)
        elif search_type == "by_status":
            return self._search_by_status(order_status=search_params)
        else:
            return ajax_response.bad_request()

    def _search_by_id(self, order_pk):
        """
        Ищет заказ по ID.

        Args:
            order_pk (str): ID заказа для поиска.

        Returns:
            JsonResponse: JSON-ответ с результатом поиска или ошибкой.
        """
        if not order_pk.isnumeric():
            return ajax_response.bad_request_with_message("Должно быть целым числом")

        try:
            order = self.model.objects.get(pk=order_pk)
            return ajax_response.success_request(
                message=f"Найден заказ №{order.pk}\n",
                link=order.get_absolute_url()
            )
        except self.model.DoesNotExist:
            return ajax_response.not_found(f"Заказ {order_pk} не найден.")

    def _search_by_table(self, table_id):
        """
        Ищет заказ по номеру стола.

        Args:
            table_id (str): Номер стола для поиска.

        Returns:
            JsonResponse: JSON-ответ с результатом поиска или ошибкой.
        """

orders/templates/orders/base.html
{% load static %}
<!doctype html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'orders/css/style.css' %}">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script
        src="https://code.jquery.com/jquery-3.7.1.min.js"
        integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo="
        crossorigin="anonymous">
    </script>
    <link rel="icon" href="{% static 'orders/favicon.png' %}" type="image/x-icon">
    <title>{% block title %}Title{% endblock %}</title>
</head>
<body>
{% block nvbar %}
{% include 'orders/incl/navbar.html' %}
{% endblock %}

{% block content %}
<div class="">Тут основной контент</div>
{% endblock %}

<div class="alert base-alert" role="alert" style="display: none;">
    A simple success alert—check it out!
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>


<script src="{% static 'orders/js/base_script.js' %}"></script>
{% block custom_js %}{% endblock %}
</body>
</html>

orders/templates/orders/home_page.html
{% extends 'orders/base.html' %}

{% block title %}Главная страница{% endblock %}

{% block content %}

<div class="container mt-3">
    <h3>Управление заказами.</h3>
    <h5>Выберите действие.</h5>

    <div class="menu-links mt-3">
        <a href="{% url 'orders:orders_list' %}" class="btn btn-warning">Все заказы</a> <br>
        <a href="{% url 'orders:create_order' %}" class="btn btn-warning mt-3" target="_blank">
            Добавить заказ
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-plus-circle" viewBox="0 0 16 16">
                <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14m0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16"></path>
                <path d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4"></path>
            </svg>
        </a>
    </div>
</div>

{% endblock %}

orders/templates/orders/order_create.html
{% extends 'orders/base.html' %}

{% block title %}Создание заказа{% endblock %}

{% block content %}

<div class="container mt-5">
    <h3>Создание нового заказа.</h3>
    <form action="#" method="post">
        {% csrf_token %}
        <!-- Поле для номера стола -->
        <div class="mb-3">
            <label for="{{ form.table_number.id_for_label }}" class="form-label">Номер стола</label>
            {{ form.table_number }}
            {% if form.table_number.errors %}
                <div class="alert alert-danger mt-2">
                    {{ form.table_number.errors }}
                </div>
            {% endif %}
        </div>

        <!-- Поле для выбора блюд -->
        <div class="mb-3">
            <label class="form-label">Выберите блюда:</label>
            <div>
                {% for item in form.items %}
                    <div class="form-check">
                        {{ item.tag }}
                        <label class="form-check-label" for="{{ item.id_for_label }}">
                            {{ item.choice_label }}
                        </label>
                    </div>
                {% endfor %}
            </div>
            {% if form.items.errors %}
                <div class="alert alert-danger mt-2">
                    {{ form.items.errors }}
                </div>
            {% endif %}
        </div>

        <button type="submit" class="btn btn-success">Создать заказ</button>
    </form>
</div>

{% endblock %}

orders/templates/orders/order_detail.html
{% extends 'orders/base.html' %}
{% load static %}

{% block title %}
Заказ №{{ order.id }}
{% endblock %}

{% block content %}

<div class="container pt-3 pb-5">
    <h4 class="text-center">Информация о заказе №{{ order.id }}</h4>
    <div class="card order-list-card mt-4">
        <div class="card-header">
          Заказ ID: {{ order.id }}
        </div>
        <div class="card-body">
          <div class="">
            <div class="card-title d-flex flex-row align-items-end"> 
              <span class="text-muted">
                  <h5>Статус заказа:</h5>
              </span> 
              <span class="actual-order-status order-status-{{ order.status }} ms-2">
              <h5> {{ order.get_status_display }}</h5>
              </span> 
              <select id="changeOrderStatusSelects" class="form-select d-none w-25 ms-2" aria-label="Default select example">
                <option class="order-status-option" value="pending">В ожидании</option>
                <option class="order-status-option" value="ready">Готово</option>
                <option class="order-search-option" value="paid">Оплачено</option>
              </select>
              <form id="changeOrderStatusForm" action="{{ url_for_change_order_status }}" data-csrf_token="{{ csrf_token }}" method="post">
                <input id="newOrderStatusInput" type="hidden" name="new_status">
                <button id="confirmChangeOrderStatusButton" class="btn btn-success d-none ms-2" type="submit">Сохранить</button>
                <button id="cancelChangeOrderStatusButton" class="btn btn-warning d-none ms-2" type="">Отменить</button>
              </form>
              <div class="mb-2"><a href="" id="changeOrderStatusButton" class="ms-2">Изменить статус</a></div>
            </div>
          </div>

          <h5 class="card-title">
            <span class="text-muted">
                Номер стола:
            </span> 
            {{ order.table_number }}
          </h5>
          <h5 class="card-title">
            <span class="text-muted">
                Общая стоимость: 
            </span> 
            <b>{{ order.total_price|floatformat:0 }} ₽</b>
          </h5>
          <h5 class="card-title">
            <hr class="hr" />
            <span class="text-muted">
                Список блюд:
            </span> 
          </h5>

          <!-- Items list -->
          <table class="table">
            <thead>
              <tr>
                <th scope="col">#</th>
                <th scope="col">Название</th>
                <th scope="col">Стоимость</th>
              </tr>
            </thead>
            <tbody>
              {% for item in order.items.all %}
              <tr>
                <th scope="row">{{ forloop.counter }}</th>
                <td>{{ item.name }}</td>
                <td>{{ item.price|floatformat:'0' }} ₽</td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
          <!-- /Items list -->

          <button id="openModalForDeleteButton" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#confirmDeleteOrderModal">Удалить заказ</button>
        </div>
      </div>

    <!-- Modal -->
    <div class="modal fade" id="confirmDeleteOrderModal" tabindex="-1" aria-labelledby="confirmDeleteOrderModalLabel" aria-hidden="true">
        <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
            <h5 class="modal-title" id="confirmDeleteOrderModalLabel">Подтверждение удаления закза</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                Вы точно хотите удалить заказ №{{ order.id }}? При нажатии на кнопку "Да" заказ и вся информация о нем будут удалены!
            </div>
            <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Закрыть</button>
            <button id="deleteOrderConfirmButton" 
                    type="button" 
                    data-del_order_url="{% url 'orders:delete_order' order.pk %}" 
                    data-csrf="{{ csrf_token }}" 
                    data-url_redirect_after_delete="{% url 'orders:orders_list' %}"
                    class="btn btn-danger">
                    Да
            </button>
            </div>
        </div>
        </div>
    </div>

    <a href="{% url 'orders:orders_list' %}" class="btn btn-primary mt-3">
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-left" viewBox="0 0 16 16">
        <path fill-rule="evenodd" d="M15 8a.5.5 0 0 0-.5-.5H2.707l3.147-3.146a.5.5 0 1 0-.708-.708l-4 4a.5.5 0 0 0 0 .708l4 4a.5.5 0 0 0 .708-.708L2.707 8.5H14.5A.5.5 0 0 0 15 8"/>
        </svg>
         К списку заказов
    </a>

</div>

{% endblock %}

{% block custom_js %}
<script src="{% static 'orders/js/order_detail_script.js' %}"></script>
{% endblock %}

orders/templates/orders/orders_list.html
{% extends 'orders/base.html' %}
{% load static %}

{% block title %}
{% if status %}
Заказы со статусом "{{ status }}"
{% else %}
Все заказы
{% endif %}
{% endblock %}

{% block content %}


<div class="container pt-3 pb-5">
    {% if status %}
    <h3>Заказы со статусом "{{ status }}"</h3>
    {% else %}
    <h3>Все заказы</h3>
    {% endif %}

    {% for order in orders %}
    <div class="card order-list-card mt-4">
        <div class="card-header">
          Заказ ID: {{ order.id }}
        </div>
        <div class="card-body">
          <h5 class="card-title"> 
            <span class="text-muted">
                Статус заказа:
            </span> 
            <span class="order-status-{{ order.status }}">
            {{ order.get_status_display }}
            </span>
          </h5>
          <h5 class="card-title">
            <span class="text-muted">
                Номер стола:
            </span> 
            {{ order.table_number }}
          </h5>
          <h5 class="card-title">
            <span class="text-muted">
                Общая стоимость: 
            </span> 
            <b>{{ order.total_price|floatformat:0 }} ₽</b>
          </h5>
          <h5 class="card-title">
            <hr class="hr" />
            <span class="text-muted">
                Список блюд:
            </span> 
          </h5>

          <!-- Items list -->
          <table class="table">
            <thead>
              <tr>
                <th scope="col">#</th>
                <th scope="col">Название</th>
                <th scope="col">Стоимость</th>
              </tr>
            </thead>
            <tbody>
              {% for item in order.items.all %}
              <tr>
                <th scope="row">{{ forloop.counter }}</th>
                <td>{{ item.name }}</td>
                <td>{{ item.price }}</td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
          <!-- /Items list -->

          <a href="{{ order.get_absolute_url }}" class="btn btn-primary">Открыть</a>
        </div>
      </div>

    {% empty %}
    {% if not status %}
    <div class="container text-center">
      <h4>Тут пока нет заказов.</h4>
      <a href="{% url 'orders:create_order' %}" class="btn btn-warning">Создать первый заказ</a>
    </div>
    {% endif %}
    {% endfor %}
</div>

{% endblock %}


{% block custom_js %}
<script src="{% static 'orders/js/homepage_script.js' %}"></script>
{% endblock %}