cafeorders/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("orders.urls", namespace="orders")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter

from orders.views import (home_page, UpdateOrderView,
                          calculate_total_revenue, OrderListView,
                          OrderDetailView, CreateOrderView,
                          DeleteOrderView, SearchOrderView)
from orders.api_views import OrderViewSet, ItemViewSet

app_name = "orders"

router = DefaultRouter()
router.register(r'orders', OrderViewSet)
router.register(r'items', ItemViewSet)

urlpatterns = [
    path("", home_page, name="home_page"),

    path("orders/", OrderListView.as_view(),
         name="orders_list"),
    path("orders/order/<int:order_pk>",
         OrderDetailView.as_view(),
         name="order_detail"),
    path("orders/order/create_order",
         CreateOrderView.as_view(),
         name="create_order"),
    path('api/', include(router.urls))
]

ajax_urls = [
    path("orders/ajax/search_order/",
         SearchOrderView.as_view(),
         name="search_order"),
    path("orders/ajax/change_order_status/<int:order_pk>",
         UpdateOrderView.as_view(),
         name="change_order_status"),
    path("orders/order/delete_order/<int:order_pk>",
         DeleteOrderView.as_view(),
         name="delete_order"),
    path("orders/ajax/calculate_total_revenue",
         calculate_total_revenue,
         name="calculate_total_revenue"
         )
]

urlpatterns += ajax_urls

orders/models.py
from django.db import models
from django.shortcuts import reverse

class Item(models.Model):
    name = models.CharField(max_length=155,
                            verbose_name="Название")
    price = models.DecimalField(max_digits=8,
                                decimal_places=2,
                                verbose_name="Стоимость")

    def __str__(self):
        return f"Блюдо: {self.name}. Стоимость: {self.price}"

    class Meta:
        verbose_name = "Блюдо"
        verbose_name_plural = "Блюда"


class Order(models.Model):
    STATUS_CHOICES = [
        ('pending', 'В ожидании'),
        ('ready', 'Готово'),
        ('paid', 'Оплачено'),
    ]

    table_number = models.PositiveIntegerField(verbose_name="Номер стола",
                                               unique=True)
    total_price = models.DecimalField(max_digits=10,
                                      decimal_places=2,
                                      default=0,
                                      verbose_name="Сумма заказа")
    status = models.CharField(max_length=7,
                              choices=STATUS_CHOICES,
                              default="pending", verbose_name="Статус")
    items = models.ManyToManyField(to=Item)

    def __str__(self):
        return f"Заказ #{self.id}. Статус: {self.status}"

    def get_absolute_url(self):
        return reverse("orders:order_detail", kwargs={
            "order_pk": self.pk
        })

    class Meta:
        verbose_name = "Заказ"
        verbose_name_plural = "Заказы"

orders/forms.py
from django import forms
from django.core.exceptions import ValidationError

from orders.models import Order, Item


class CreateOrderForm(forms.ModelForm):
    items = forms.ModelMultipleChoiceField(
        queryset=Item.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        error_messages={
            'required': 'Заказ не может быть пустым.',  # Кастомное сообщение
        }
    )

    class Meta:
        model = Order
        fields = ["table_number", "items"]
        widgets = {
            "table_number": forms.NumberInput(attrs={
                'class': 'form-control w-25',
                'placeholder': 'Номер стола'
            }),
        }

orders/views.py
import json
from django.views import View
from django.http import HttpRequest, HttpResponse, HttpResponseRedirect, QueryDict
from django.http.response import HttpResponseNotAllowed
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse
from django.db.models import Sum
from orders.models import Order
from orders.forms import CreateOrderForm
from orders.ajax_responses import ajax_response


def home_page(request: HttpRequest):
    """
    Отображает главную страницу приложения.

    Args:
        request (HttpRequest): Объект запроса Django.

    Returns:
        HttpResponse: Рендер шаблона главной страницы.
        HttpResponseNotAllowed: Если метод запроса не GET.
    """
    if request.method != "GET":
        return HttpResponseNotAllowed(permitted_methods=["GET"])

    return render(request, "orders/home_page.html")


class BaseOrderView(View):
    """
    Базовый класс для views, работающих с заказами

    Attributes:
        model: Модель, с которой работает View (Order)
        form_class: Класс формы для создания нового заказа
        template_name (str): Имя шаблона для рендера (определяется в дочерних классах)
    """
    model = Order
    form_class = CreateOrderForm
    template_name = None

    def get_context_data(self, **kwargs):
        """
        Возвращает контекст для шаблонов

        Args:
            **kwargs: Дополнительные данные для контекста.

        Returns:
            dict: Контекст для шаблона.
        """
        return kwargs


class OrderListView(BaseOrderView):
    """
    View для отображения списка заказов

    Attributes:
        template_name (str): Имя шаблона для отображения списка заказов.
    """
    template_name = "orders/orders_list.html"

    def get(self, request: HttpRequest, *args, **kwargs):
        """
        Обрабатывает GET-запрос для отображения списка заказов.

        Если в запросе передан параметр 'status', возвращает заказы с указанным статусом.

        Args:
            request (HttpRequest): Объект запроса Django.
            *args: Дополнительные позиционные аргументы.
            **kwargs: Дополнительные именованные аргументы.

        Returns:
            HttpResponse: Рендер шаблона с контекстом, содержащим список заказов.

        """
        status = request.GET.get("status")
        if status:
            orders = self.model.objects.filter(status=status)
            status = dict(Order.STATUS_CHOICES).get(status)
        else:
            orders = self.model.objects.all()

        context = self.get_context_data(orders=orders, status=status)

        return render(request, self.template_name, context=context)


class OrderDetailView(BaseOrderView):
    """
    View для отображения деталей конкретного заказа.

    Attributes:
        template_name (str): Имя шаблона для отображения деталей заказа.
    """
    template_name = "orders/order_detail.html"

    def get(self, request: HttpRequest, order_pk: int, *args, **kwargs):
        """
        Обрабатывает GET-запрос для отображения деталей заказа.

        Args:
            request (HttpRequest): Объект запроса Django.
            order_pk (int): ID заказа.
            *args: Дополнительные позиционные аргументы.
            **kwargs: Дополнительные именованные аргументы.

        Returns:
            HttpResponse: Рендер шаблона с контекстом, содержащим данные заказа и URL для изменения статуса.
        """
        order = get_object_or_404(
            klass=self.model, pk=order_pk
        )

        context = self.get_context_data(
            order=order,
            url_for_change_order_status=reverse(
                "orders:change_order_status", args=[order.pk]
            )
        )
        return render(request,
                      self.template_name,
                      context=context
                      )


class CreateOrderView(BaseOrderView):
    """
    View для создания нового заказа.

    Attributes:
        template_name (str): Имя шаблона для отображения формы создания заказа.
    """
    template_name = "orders/order_create.html"

    def get(self, request: HttpRequest):
        """
        Обрабатывает GET-запрос для отображения формы создания заказа.

        Args:
            request (HttpRequest): Объект запроса Django.

        Returns:
            HttpResponse: Рендер шаблона с формой создания заказа.
        """
        form = self.form_class()
        context = self.get_context_data(
            form=form
        )
        return render(request,
                      self.template_name,
                      context=context
                      )

    def post(self, request: HttpRequest, *args, **kwargs):
        """
        Обрабатывает POST-запрос для создания нового заказа.

        Если данные формы валидны, создает заказ и перенаправляет на его детальную страницу.
        Иначе возвращает форму с ошибками.

        Args:
            request (HttpRequest): Объект запроса Django.
            *args: Дополнительные позиционные аргументы.
            **kwargs: Дополнительные именованные аргументы.

        Returns:
            HttpResponseRedirect: Перенаправление на страницу созданного заказа.
            HttpResponse: Рендер шаблона с формой, если данные невалидны.
        """
        form = self.form_class(request.POST)
        if form.is_valid():
            new_order = form.save()
            redirect_url = reverse("orders:order_detail", args=[new_order.pk])
            return redirect(redirect_url)
        context = self.get_context_data(form=form)
        return render(request, self.template_name, context=context)


# Views для AJAX

class DeleteOrderView(BaseOrderView):
    """
    View для удаления заказа.
    """
    def delete(self, request: HttpRequest, order_pk: int, *args, **kwargs):
        """
        Обрабатывает DELETE-запрос для удаления заказа.

        Args:
            request (HttpRequest): Объект запроса Django.
            order_pk (int): ID заказа для удаления.
            *args: Дополнительные позиционные аргументы.
            **kwargs: Дополнительные именованные аргументы.

        Returns:
            JsonResponse: JSON-ответ с результатом операции.
        """
        try:
            order = self.model.objects.get(pk=order_pk)
        except self.model.DoesNotExist:
            return ajax_response.not_found(
                message="Заказ не найден"
            )

        order.delete()
        return ajax_response.success_request(
            message=f"Заказ №{order_pk} удален.\nСейчас вы будете перенаправлены к списку заказов."
        )


class UpdateOrderView(BaseOrderView):
    """
    View для изменения статуса заказа
    """
    def patch(self, request: HttpRequest, order_pk):
        """
        Обрабатывает PATCH-запрос для изменения статуса заказа.

        Args:
            request (HttpRequest): Объект запроса Django.
            order_pk (int): ID заказа для обновления.

        Returns:
            JsonResponse: JSON-ответ с результатом операции.
        """
        allowed_statuses = dict(Order.STATUS_CHOICES)

        try:
            data = json.loads(request.body.decode('utf-8'))
            new_status = data.get("new_status")
        except json.JSONDecodeError:
            return ajax_response.bad_request()

        if not new_status or new_status not in allowed_statuses.keys():
            return ajax_response.bad_request()

        try:
            order = self.model.objects.get(pk=order_pk)
        except self.model.DoesNotExist:
            return ajax_response.not_found(
                message=f"Заказ не найден"
            )
        order.status = new_status
        order.save()
        return ajax_response.success_request(
            message=f"Статус успешно обновлен_{allowed_statuses.get(new_status)}"
        )


class SearchOrderView(BaseOrderView):
    """
    View для поиска заказов по ID, номеру стола или статусу.
    """
    def get(self, request: HttpRequest, *args, **kwargs):
        """
        Обрабатывает GET-запрос для поиска заказов.

        Args:
            request (HttpRequest): Объект запроса Django.
            *args: Дополнительные позиционные аргументы.
            **kwargs: Дополнительные именованные аргументы.

        Returns:
            JsonResponse: JSON-ответ с результатами поиска или ошибкой.
        """

        search_type = request.GET.get("orderSearchType")
        search_params = request.GET.get("search_val")

        if not search_type or not search_params:
            return ajax_response.bad_request_with_message(
                message="No required parameters"
            )

        if search_type == "by_id":
            return self._search_by_id(order_pk=search_params)
        elif search_type == "by_table":
            return self._search_by_table(table_id=search_params)
        elif search_type == "by_status":
            return self._search_by_status(order_status=search_params)
        else:
            return ajax_response.bad_request()

    def _search_by_id(self, order_pk):
        """
        Ищет заказ по ID.

        Args:
            order_pk (str): ID заказа для поиска.

        Returns:
            JsonResponse: JSON-ответ с результатом поиска или ошибкой.
        """
        if not order_pk.isnumeric():
            return ajax_response.bad_request_with_message("Должно быть целым числом")

        try:
            order = self.model.objects.get(pk=order_pk)
            return ajax_response.success_request(
                message=f"Найден заказ №{order.pk}\n",
                link=order.get_absolute_url()
            )
        except self.model.DoesNotExist:
            return ajax_response.not_found(f"Заказ {order_pk} не найден.")

    def _search_by_table(self, table_id):
        """
        Ищет заказ по номеру стола.

        Args:
            table_id (str): Номер стола для поиска.

        Returns:
            JsonResponse: JSON-ответ с результатом поиска или ошибкой.
        """

orders/templates/orders/incl/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'orders:home_page' %}">На главную</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Заказы
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <li><a class="dropdown-item" href="{% url 'orders:orders_list' %}">Все заказы</a></li>
            <li><a class="dropdown-item" href="{% url 'orders:create_order' %}" target="_blank">
              Добавить заказ
              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-plus-circle" viewBox="0 0 16 16">
                <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14m0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16"/>
                <path d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4"/>
              </svg>
            </a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a href="" 
          class="nav-link"
          id="calculateRevenueButton"
          data-url-for-calculate-revenue="{% url 'orders:calculate_total_revenue' %}" 
          >
            Выручка ₽
          </a>
        </li>
      </ul>
    </div>

    <div class="input-group w-50 orders-search-inputs justify-content-end flex-nowrap">
      <div class="" style="margin: auto 15px auto; white-space: nowrap; color: white;">
        Поиск заказов
      </div>
      <button id="buttonForChangeSearchType" 
        class="btn btn-outline-secondary dropdown-toggle rounded-0 text-light" 
        type="button" 
        data-bs-toggle="dropdown"
        
        aria-expanded="false">
        по номеру стола
      </button>
      <ul class="dropdown-menu">
        <li><a class="dropdown-item order-search-type" data-order_search_type="by_id" href="#">по ID</a></li>
        <li><a class="dropdown-item order-search-type" data-order_search_type="by_table" href="#">по номеру стола</a></li>
        <li><a class="dropdown-item order-search-type" data-order_search_type="by_status" href="#">по статусу</a></li>
      </ul>
      <form id="navbarSearchOrderForm" class="d-flex" data-navbar_search_url="{% url 'orders:search_order' %}">
        <input id="orderSearchTypeInput" type="hidden" name="orderSearchType" value="by_table">
        <input id="orderSearchInput" required type="text" class="form-control rounded-0" aria-label="" name="search_val">
        <select id="orderSearchByStatusSelect" class="form-select rounded-0 d-none" aria-label="Default select example">
          <option class="order-search-option" value="pending">В ожидании</option>
          <option class="order-search-option" value="ready">Готово</option>
          <option class="order-search-option" value="paid">Оплачено</option>
        </select>

        <button class="btn btn-outline-warning rounded-0" type="submit">Искать</button>
      </form>
    </div>
  </div>

  <div id="navbarToast" class="toast navbar-toast p-3" role="alert" aria-live="assertive" aria-atomic="true">
    <div class="toast-header justify-content-between rounded-1">
      <div class="navbar-toast-message"></div>
      <button type="button" class="btn-close" data-bs-dismiss="toast" aria-label="Close"></button>
    </div>
  </div>
  
</nav>